### PR TITLE
Set bindgen version to 0 to avoid linking error

### LINKED ISSUE #2: Bindgen linking error
Seems like this can be mitigated by not using specific versions at build-dependencies for.

Bindgen error:

```bash
    Updating crates.io index
error: failed to select a version for `clang-sys`.
    ... required by package `bindgen v0.48.1`
    ... which is depended on by `audiopus_sys v0.1.0`
    ... which is depended on by `audiopus v0.1.0`
    ... which is depended on by `netsound v0.1.0 (/Users/mozgiii/Desktop/netsound)`
versions that meet the requirements `^0.26.4` are: 0.26.4

the package `clang-sys` links to the native library `clang`, but it conflicts with a previous package which links to `clang` as well:
package `clang-sys v0.28.0`
    ... which is depended on by `bindgen v0.51.0`
    ... which is depended on by `netsound v0.1.0 (/Users/mozgiii/Desktop/netsound)`
```

### PR DESCRIPTION
**Pull request by MOZGIII**
This is a hack, but it's the best we can do for now
Closes #2

### CODE REVIEW

**Comment by Lakelezz** [comment]
Thanks for your pull request!

Please set the version to the latest minor version and omit the patch instead of just `"0"`.

**Comment by MOZGIII** [comment]
This isn't going work (for me at least) because of semantic versioning logic: before version `1` no versions are considered compatible, so in that sense it should make no difference. To elaborate: version `0.51` would not be compatible with `0.52`, and we'd end up with the same outcome. The only real solution currently (even though it's unsound) is to have it depend on `0` or `*`.

**Comment by Lakelezz** [comment]
Rust uses a modified SemVer, take a look for compatibility before 1.0.0 here: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html?highlight=semver#caret-requirements

**Comment by Lakelezz** [comment]
Rust uses a modified SemVer, take a look for compatibility before 1.0.0 here: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements

**Comment by MOZGIII** [comment]
What's your point?

**Comment by MOZGIII** [comment]
The core issue the `bindgen` is conflicting with other dependencies that are also using `bindgen`. If some dependency requires `bindgen` `0.51`, and some other requires `0.52`, there's no version that can be used, even though it's usually ok with `bindgen` in particular.

**Comment by Lakelezz** [comment]
Thanks for the pull request. However, this could be resolved in a different way, see #2.

**Pull request closed without merging**
